default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    # 1. Authenticate with Apple using your GitHub Secrets
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      in_house: false
    )

    # 2. Build the iOS Archive (IPA)
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' DEVELOPMENT_TEAM='W98N32D5AW'"
    )

    # 3. Upload the IPA to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
