default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    # 1. Authenticate with Apple using your GitHub Secrets
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      in_house: false
    )

    # 2. Update Code Signing Settings for the main target
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      team_id: "W98N32D5AW",
      bundle_identifier: "com.aarambhait.lumoranine",
      code_sign_identity: "Apple Distribution",
      profile_name: ENV["PROVISIONING_PROFILE_NAME"],
      profile_uuid: ENV["PROVISIONING_PROFILE_UUID"]
    )

    # 3. Build the iOS Archive (IPA)
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.aarambhait.lumoranine" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      }
    )

    # 3. Upload the IPA to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
